version: '3.8'

services:
  web:
    image: api-project
    env_file:
      - .env
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - .:/usr/src/app
    networks:
      - api-network
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - api-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  api-network:
    driver: bridge